/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeadBar: typeof import('./components/ui/AppHeadBar.vue')['default']
    AppHeaderBar: typeof import('./components/ui/AppHeaderBar.vue')['default']
    AppNavigationDrawer: typeof import('./components/ui/AppNavigationDrawer.vue')['default']
    Card: typeof import('./components/ui/Card.vue')['default']
    FightScoreTimelineItem: typeof import('./components/FightScoreTimelineItem.vue')['default']
    FightTimelineScore: typeof import('./components/FightTimelineScore.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    MarkingComponent: typeof import('./components/marking/MarkingComponent.vue')['default']
    MatchesHistoryTable: typeof import('./components/match/MatchesHistoryTable.vue')['default']
    MatchOverview: typeof import('./components/match/MatchOverview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreMarkingDialog: typeof import('./components/marking/ScoreMarkingDialog.vue')['default']
    ScoreTimelineItem: typeof import('./components/ScoreTimelineItem.vue')['default']
  }
}
