/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeaderBar: typeof import('./components/ui/AppHeaderBar.vue')['default']
    AppNavigationDrawer: typeof import('./components/ui/AppNavigationDrawer.vue')['default']
    Card: typeof import('./components/ui/Card.vue')['default']
    CreateFencerDialog: typeof import('./components/dialogs/CreateFencerDialog.vue')['default']
    CreateUserDialog: typeof import('./components/dialogs/CreateUserDialog.vue')['default']
    Dialog: typeof import('./components/ui/Dialog.vue')['default']
    FightScoreTimelineItem: typeof import('./components/FightScoreTimelineItem.vue')['default']
    MarkingComponent: typeof import('./components/marking/MarkingComponent.vue')['default']
    MatchesFilterDialog: typeof import('./components/dialogs/MatchesFilterDialog.vue')['default']
    MatchFencerOverview: typeof import('./components/match/MatchFencerOverview.vue')['default']
    MatchOverview: typeof import('./components/match/MatchOverview.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScoreEditDialog: typeof import('./components/dialogs/ScoreEditDialog.vue')['default']
    ScoreHistoryDialog: typeof import('./components/dialogs/ScoreHistoryDialog.vue')['default']
    ScoreMarkingDialog: typeof import('./components/marking/ScoreMarkingDialog.vue')['default']
  }
}
