/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/fencers/': RouteRecordInfo<'/fencers/', '/fencers', Record<never, never>, Record<never, never>>,
    '/fights/': RouteRecordInfo<'/fights/', '/fights', Record<never, never>, Record<never, never>>,
    '/fights/[id]/': RouteRecordInfo<'/fights/[id]/', '/fights/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/fights/[id]/manage': RouteRecordInfo<'/fights/[id]/manage', '/fights/:id/manage', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/fights/create': RouteRecordInfo<'/fights/create', '/fights/create', Record<never, never>, Record<never, never>>,
    '/score-profiles/': RouteRecordInfo<'/score-profiles/', '/score-profiles', Record<never, never>, Record<never, never>>,
    '/score-profiles/[id]/': RouteRecordInfo<'/score-profiles/[id]/', '/score-profiles/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/users/': RouteRecordInfo<'/users/', '/users', Record<never, never>, Record<never, never>>,
  }
}
